CREATE TABLE STUDENT (
    USN VARCHAR(20) PRIMARY KEY,
    SName VARCHAR(100) NOT NULL,
    Address VARCHAR(200) NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    Gender VARCHAR(10) NOT NULL
);

CREATE TABLE SEMSEC (
    SSID INT PRIMARY KEY,
    Sem INT NOT NULL,
    Sec VARCHAR(10) NOT NULL
);


CREATE TABLE CLASS (
    USN VARCHAR(20) NOT NULL,
    SSID INT NOT NULL,
    PRIMARY KEY (USN, SSID),
    FOREIGN KEY (USN) REFERENCES STUDENT (USN),
    FOREIGN KEY (SSID) REFERENCES SEMSEC (SSID)
);


CREATE TABLE SUBJECT (
    Subcode VARCHAR(20) PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Sem INT NOT NULL,
    Credits INT NOT NULL
);


CREATE TABLE IAMARKS (
    USN VARCHAR(20) NOT NULL,
    Subcode VARCHAR(20) NOT NULL,
    SSID INT NOT NULL,
    Test1 DECIMAL(5, 2) NOT NULL,
    Test2 DECIMAL(5, 2) NOT NULL,
    Test3 DECIMAL(5, 2) NOT NULL,
    FinalIA DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY (USN, Subcode, SSID),
    FOREIGN KEY (USN) REFERENCES STUDENT (USN),
    FOREIGN KEY (Subcode) REFERENCES SUBJECT (Subcode),
    FOREIGN KEY (SSID) REFERENCES SEMSEC (SSID)
);



INSERT INTO STUDENT VALUES ('1RN13CS020','AKSHAY','BELAGAVI', 8877881122,'M');
INSERT INTO STUDENT VALUES('1RN13CS062','SANDHYA','BENGALURU', 7722829912,'F'); 
INSERT INTO STUDENT VALUES('1RN13CS091','TEESHA','BENGALURU', 7712312312,'F'); 
INSERT INTO STUDENT VALUES('1RN13CS066','SUPRIYA','MANGALURU', 8877881122,'F'); 
INSERT INTO STUDENT VALUES('1RN14CS010','ABHAY','BENGALURU', 9900211201,'M');


INSERT INTO SEMSEC VALUES ('CSE8A', 8,'A'); 
INSERT INTO SEMSEC VALUES ( ̳CSE8B', 8,'B'); 
INSERTINTOSEMSECVALUES( ̳CSE8C‘,8,‘C‘);
INSERT INTO SEMSEC VALUES ('CSE7A', 7,‘A‘); 
INSERTINTOSEMSECVALUES( ̳CSE7B‘,7,'B‘); 
INSERT INTO SEMSEC VALUES ('CSE7C',7,'C');
INSERT INTO SEMSEC VALUES ( ̳CSE6A', 6,'A'); 
INSERT INTO SEMSEC VALUES ( ̳CSE6B‘, 6,‘B‘); 
INSERT INTO SEMSEC VALUES ('CSE6C‘, 6,‘C‘);



INSERTINTOCLASSVALUES( ̳1RN13CS020‘,‘CSE8A ‘); INSERTINTOCLASSVALUES( ̳1RN13CS062‘,‘CSE8A ‘); INSERTINTOCLASSVALUES( ̳1RN13CS066‘,‘CSE8B ‘); INSERTINTOCLASSVALUES( ̳1RN13CS091‘,‘CSE8C ‘);
INSERTINTOCLASSVALUES( ̳1RN14CS010‘,‘CSE7A ‘); INSERTINTOCLASSVALUES( ̳1RN14CS025‘,‘CSE7A ‘); INSERTINTOCLASSVALUES( ̳1RN14CS032‘,‘CSE7A ‘);
INSERTINTOCLASSVALUES( ̳1RN15CS011‘,‘CSE4A ‘); INSERTINTOCLASSVALUES( ̳1RN15CS029‘,‘CSE4A


INSERT INTO SUBJECT VALUES ('10CS81','ACA', 8, 4); 
INSERT INTO SUBJECT VALUES ('10CS82','SSM', 8, 4); INSERT INTO SUBJECT VALUES ('10CS83','NM', 8, 4); 
INSERT INTO SUBJECT VALUES ('10CS84','CC', 8, 4); INSERT INTO SUBJECT VALUES ('10CS85','PW', 8, 4);



INSERT INTO IAMARKS (USN, SUBCODE, SSID, TEST1, TEST2,TEST3)VALUES ('1RN13CS091','10CS81','CSE8C', 15, 16,18);
INSERT INTO IAMARKS (USN, SUBCODE, SSID, TEST1, TEST2,TEST3)VALUES ('1RN13CS091','10CS82','CSE8C', 12, 19,14);
INSERT INTO IAMARKS (USN, SUBCODE, SSID, TEST1, TEST2,TEST3)VALUES ('1RN13CS091','10CS83','CSE8C', 19, 15,20);
INSERT INTO IAMARKS (USN, SUBCODE, SSID, TEST1, TEST2,TEST3)VALUES ('1RN13CS091','10CS84','CSE8C', 20, 16,19);
INSERT INTO IAMARKS (USN, SUBCODE, SSID, TEST1, TEST2,TEST3)VALUES ('1RN13CS091','10CS85','CSE8C', 15, 15,12);



-- List all the student details studying in fourth semester ‘C’section.
SELECT S.*, SS.SEM, SS.SEC
FROM STUDENT S, SEMSEC SS, CLASS C WHERE S.USN = C.USN AND SS.SSID = C.SSID
AND SS.SEM = 4 AND
SS.SEC=‘C‘;

-- Compute the total number of male and female students in each semester and in eachsection.

SELECT SS.SEM, SS.SEC, S.GENDER, COUNT (S.GENDER) AS COUNT FROM STUDENT S, SEMSEC SS, CLASS C
WHERES.USN =
C.USNAND SS.SSID
=C.SSID
GROUP BY SS.SEM, SS.SEC, S.GENDER ORDER BYSEM;

-- Create a view of Test1 marks of student USN ‘1BI15CS101’ in allsubjects.

CREATE VIEW
STU_TEST1_MARKS_VIEW AS SELECT
TEST1, SUBCODE
FROM IAMARKS
WHERE USN = '1RN13CS091';

-- Calculate the FinalIA (average of best two test marks) and update the corresponding table for allstudents.
UPDATE IAMARKS I
SET FinalIA = (
    SELECT (Test1 + Test2 + Test3 + FinalIA - LEAST(Test1, Test2, Test3, FinalIA)) / 3
    FROM (
        SELECT Test1, Test2, Test3, FinalIA
        FROM IAMARKS
        WHERE USN = I.USN AND Subcode = I.Subcode AND SSID = I.SSID
        ORDER BY Test1 DESC, Test2 DESC, Test3 DESC, FinalIA DESC
        LIMIT 2
    ) AS BestTwo
)
WHERE EXISTS (
    SELECT 1
    FROM IAMARKS
    WHERE USN = I.USN AND Subcode = I.Subcode AND SSID = I.SSID
);






-- Categorize students based on the followingcriterion: If FinalIA = 17 to 20 then CAT=‘Outstanding’
-- If FinalIA = 12 to 16 then CAT = ‘Average’ If FinalIA< 12 then CAT = ‘Weak’ Give these details only for
-- 8th semester A, B, and C section students.

SELECT S.USN,S.SNAME,S.ADDRESS,S.PHONE,S.GENDER, (CASE
WHEN IA.FINALIA BETWEEN 17 AND 20 THEN'OUTSTANDING' WHEN IA.FINALIA BETWEEN 12 AND 16 THEN 'AVERAGE' ELSE 'WEAK'
END) AS CAT
FROM STUDENT S, SEMSEC SS, IAMARKS IA, SUBJECT SUB WHERE S.USN = IA.USN AND SS.SSID = IA.SSID AND
SUB.SUBCODE = IA.SUBCODE
AND SUB.SEM = 8;